export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const WORKOUT_NAME_CHANGED = 'WORKOUT_NAME_CHANGED';
export const WORKOUT_DATE_CHANGED = 'WORKOUT_DATE_CHANGED';
