export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const WORKOUT_NAME_CHANGED = 'WORKOUT_NAME_CHANGED';
export const WORKOUT_DATE_CHANGED = 'WORKOUT_DATE_CHANGED';
export const CLEAR_WORKOUT_INPUT = 'CLEAR_WORKOUT_INPUT';
export const ADD_SET = 'ADD_SET';
export const SAVE_EXERCISE_TITLE = 'SAVE_EXERCISE_TITLE';
export const TITLE_CHANGED = 'TITLE_CHANGED';
